baseURL = "https://sysarmy.com/blog/"
languageCode = "en-us"
title = "El blog de quienes dan soporte"
theme = "sysarmy"
publishDir = "sysarmy.github.io/blog"
MetaDataFormat = "toml"
googleAnalytics = "UA-36359098-1"

[author]
    name = "Sysarmy"
